name: Build & Publish cyrsoxs

on:
  push:
    branches: [ main, build-in-ci ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIBW_BEFORE_BUILD: |
        rm -rf build
        mkdir build && cd build
        cmake ${PWD}/.. \
              -DCMAKE_BUILD_TYPE=Release \
              -DPYBIND=Yes \
              -DUSE_SUBMODULE_PYBIND=No
        cmake --build . --config Release
      CIBW_MANYLINUX_X86_64_IMAGE: sameli/manylinux2014_x86_64_cuda_11.8
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        run: cibuildwheel --platform linux --output-dir dist/
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.whl
          
      - name: Upload CUDA Installer Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cuda-installer-log
          path: /var/log/cuda-installer.log
