name: "Publish Documentation to NIST Pages"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.6
        with:
          docs-folder: docs/sphinx/
          apt-packages: 'doxygen'
          formats: |-
            epub
            pdf
